---
- hosts: test
  become: yes
  become_user: root
  become_method: sudo
  become_password:Welcome@2020

  tasks:
   - name: Create User Demo
     user:
      name: Demo10
      comment: Demo5 user "general user"
      group: operations
      append: yes
      password: $1$Dl6k0k59$KbZwRt2jwSm4GsR9i746q1
